name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
          targets: wasm32-wasi # WebAssembly target

    - name: Deploy examples/hello-fastly
      uses: fastly/compute-actions@v6
      with:
        project_directory: examples/hello-fastly
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
