name: Preview on Fastly

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow}}

on:
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - run: cd examples/hello-fastly
      - name: preview hello-fastly
        uses: fastly/compute-actions/preview@v6
        with:
          fastly-api-token: ${{ secrets.FASTLY_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
